# WelcomeOnJoin - WOJ
# Made by SussyMilka
# This plugin was made as a part of 90 day coding challenge.



#########################
####### MESSAGES ########
#########################
# If you dont like using in game commands, you can easily set welcome message here.
# Messages here, will be shown on chat only for user who joined.
messages:
  1: "Welcome"
  2: "Good luck!"




#########################
######## WARNING ########
#########################

#The features below are config ONLY
#and require to execute /woj reload after any change below
# (i could make it automatically update
# but that would be resource expensive)


#########################
######  TITLES  #########
#########################
#Write the message here that you want players too see on a big title in the middle of the screen.
#PlaceholderAPI is supported
#set titles_enabled to false if u dont want it
titles_enabled: true

big_title: "Welcome player!"
#Leave blank if u dont want it
subtitle: "Good luck!"

#########################
###### SOUND EFFECTS ####
#########################

# Please write true or false depending if you want sound effects
# Texturepacks and all that stuff should work, but not tested
# the code is opensource tho (:
soundeffect_enabled: true

# Please specify here what sound effect player should hear
# and find one that suits your needs.
# WARNING! TO APPLY CHANGES, A SERVER RESTART/PLUGIN RELOAD IS NEEDED
sound_effect: "entity.experience_orb.pickup"


#########################
####### STOP! ###########
#########################
# This plugin supports up to 80 messages(those in the chat) because of a Minecraft limit,
# But you can disable that lock below
# (you are only disabling this plugins limit, your messages could/will be cropped!)
limit: true
