name: WelcomeOnJoin
version: '${project.version}'
main: my.sussymilka.welcomeonjoin.WelcomeOnJoin
api-version: '1.19'
description: "Greets player on join"
author: SussyMilka
commands:
  woj:
    description: "This command is capable of setting the welcome message"
    usage: "/woj"
    permission: woj.set
permissions:
  woj.set:
    description: Allows setting a welcome message!
    default: op

softdepend: [PlaceholderAPI]